import {ILocaleStrings} from "./ILocaleStrings";

export const getEn = (): ILocaleStrings => {
    const en: ILocaleStrings = {
        TracksCount: "Tracks count",
        AverateTrackDurationS: "Averate track duration (seconds)",
        TotalPlaylistDurationS: "Total playlist duration (seconds)",
        Rating: "Rating",
        Collections: "Collections",
        ListenedBefore: "Listened before",
        Yes: "Yes",
        No: "No",
        ListenedLastWeek: "Listened last week",
        Tiers: "Tiers",
        Artists: "Artists",
        Free: "Free",
        Premium: "Premium",
        AllPossibleItemsSelected: "All possible items selected",
        Enabled: "Enabled",
        DancesKind: "Dances kind",
        Dance: "Dance",
        SingleDance: "Single dance",
        Final: "Final",
        BallroomLa: "Ballroom Latin",
        BallroomSt: "Ballroom Standard",
        Basic: "Basic",
        Advanced: "Advanced",
        Pattern: "Pattern",
        History: "History",
        TracksFilter: "Tracks filter",
        Saved: "Saved",
        Avatar: "Avatar",
        ConfirmPassword: "Confirm password",
        Name: "Name",
        SignUp: "Sign up",
        SignIn: "Sign in",
        Password: "Password",
        Email: "Email",
        Logout: "Logout",
        Artist: "Artist",
        DanceType: "DanceType",
        Foxtrot: "Foxtrot",
        Quickstep: "Quickstep",
        Save: "Save",
        Tags: "Tags",
        Tango: "Tango",
        Title: "Title",
        VienneseWaltz: "VienneseWaltz",
        Waltz: "Waltz",
        Add: "Add",
        AddTag: "Add tag",
        Cancel: "Cancel",
    };

    return en;
};
