import {ILocaleStrings} from "./ILocaleStrings";

export const getRu = (): ILocaleStrings => {
    const ru: ILocaleStrings = {
        TracksCount: "Количество треков",
        AverateTrackDurationS: "Средняя длительность трека (секунды)",
        TotalPlaylistDurationS: "Общая длительность плейлиста (секунды)",
        Rating: "Рейтинг",
        Collections: "Коллекции",
        ListenedBefore: "Слушал раньше",
        Yes: "Да",
        No: "Нет",
        ListenedLastWeek: "Прослушано за последнюю неделю",
        Tiers: "Уровни",
        Artists: "Исполнители",
        Premium: "Премиум",
        Free: "Бесплатно",
        AllPossibleItemsSelected: "Выбраны все возможные элементы",
        Enabled: "Включено",
        DancesKind: "Вид танцев",
        Dance: "Танец",
        SingleDance: "Одиночный танец",
        Final: "Финал",
        BallroomLa: "Бальные танцы - Латина",
        BallroomSt: "Бальные танцы - Стандарт",
        Basic: "Базовый",
        Advanced: "Расширенный",
        Pattern: "Паттерн",
        History: "История",
        TracksFilter: "Фильтр треков",
        Saved: "Сохранено",
        Avatar: "Аватар",
        Name: "Имя",
        ConfirmPassword: "Подтвердите пароль",
        SignIn: "Войти",
        SignUp: "Зарегистрироваться",
        Email: "Электронная почта",
        Password: "Пароль",
        Logout: "Выйти",
        Artist: "Исполнитель",
        DanceType: "Танец",
        Foxtrot: "Фокстрот",
        Quickstep: "Квикстеп",
        Save: "Сохранить",
        Tags: "Теги",
        Tango: "Танго",
        Title: "Название",
        VienneseWaltz: "Веннский вальс",
        Waltz: "Медленный Вальс",
        Add: "Добавить",
        AddTag: "Добавить тег",
        Cancel: "Отмена",
    };

    return ru;
};
