name: _ Build and deploy nodejs azure function from source

on:
  workflow_call:
    inputs:
      appName:
        required: true
        type: string
      source:
        required: true
        type: string
      slotName:
        required: false
        type: string
    secrets:
      AZUREAPPSERVICE_PUBLISHPROFILE:
        required: true

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: ${{inputs.source}} # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '18.x' # set this to the node version to use (supports 8.x, 10.x, 12.x)
  VERBOSE: true # for debugging purposes

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Resolve Project Dependencies Using Npm'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm install
          npm run build --if-present
          npm run test --if-present
          popd

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ inputs.appName }}
          slot-name: ${{ inputs.slotName }}
          package: ${{env.AZURE_FUNCTIONAPP_PACKAGE_PATH}}/../dist
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
