name: API - Dev - Build and deploy to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'api/azureFunctions/**'
      - '.github/workflows/apiDevBuildAndDeploy.yml'
      - '.github/workflows/apiBaseBuildAndDeploy.yml'
  workflow_dispatch:

jobs:
  call:
    uses: ./.github/workflows/apiBaseBuildAndDeploy.yml
    with:
      appName: 'dev-demohoster2'
      source: 'api/azureFunctions'
      slotName: 'Production'
    secrets:
      AZUREAPPSERVICE_PUBLISHPROFILE: ${{ secrets.DEV_FA_PUBLISHPROFILE }}
