name: Azure Resources - Dev - Deploy

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/azureResourcesDevDeploy.yml'
      - '.github/workflows/azureResourcesBaseDeploy.yml'
      - 'deploy/azureResources.bicep'

jobs:
  call-deploy-azure-resources:
    uses: ./.github/workflows/azureResourcesBaseDeploy.yml
    with:
      environment: 'dev'
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
