name: _ deploy azure resources from bicep

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        description: 'Azure credentials'
        required: true
      AZURE_SUBSCRIPTION_ID:
        description: 'Azure subscription id'
        required: true
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: login to azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{inputs.environment}}
          template: ./.deploy/azureResources.bicep
          parameters: 'environment=${{ inputs.environment }} hostingPlanLocation=eastus'
          failOnStdErr: false

