name: Prod - UI - Build and deploy react app to static web app

on:
  push:
    branches:
      - main
    paths:
      - 'UI/**'
      - '.github/workflows/devUIBuildAndDeploy.yml'
      - '.github/workflows/baseBuildAndDeployReactApp.yml'
    workflow_dispatch:

jobs:
  call-build-and-deploy-react-app:
    uses: ./.github/workflows/baseBuildAndDeployReactApp.yml
    with:
      app_location: "/UI"
      output_location: "dist"
    secrets:
      AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_FOREST_078577A10 }}
