name: React App - Dev - Build and deploy

on:
  push:
    branches:
      - main
    paths:
      - 'UI/**'
      - '.github/workflows/reactAppDevBuildAndDeploy.yml'
      - '.github/workflows/reactAppBaseBuildAndDeploy.yml'
    workflow_dispatch:

jobs:
  call-build-and-deploy-react-app:
    uses: ./.github/workflows/baseBuildAndDeployReactApp.yml
    with:
      app_location: "/UI"
      output_location: "dist"
    secrets:
      AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.DEV_SWA_DEPLOYMENT_TOKEN }}
