name: React App - Dev - Build and deploy

on:
  push:
    branches:
      - main
    paths:
      - 'react-app/**'
      - '.github/workflows/reactAppDevBuildAndDeploy.yml'
      - '.github/workflows/reactAppBaseBuildAndDeploy.yml'
    workflow_dispatch:

jobs:
  call:
    uses: ./.github/workflows/reactAppBaseBuildAndDeploy.yml
    with:
      app_location: "/react-app"
      output_location: "dist"
    secrets:
      AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.DEV_SWA_DEPLOYMENT_TOKEN }}
